name: signup

on:
    push:
        branches:
            - master
    schedule:
        - cron: "40 16 * * *"
jobs:
    start_sign:
        name: start_daily_sign
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
            - uses: actions/setup-node@v2-beta
              with:
                node-version: '14'
            - name: Sign skunkgirl
              shell: bash
              env:
                LINE_USERID: ${{ secrets.LINE_USERID }}
                LINECHANNEL: ${{ secrets.LINECHANNEL }}
                LINESECRET: ${{ secrets.LINESECRET }}
                LINECHANNELTOKEN: ${{ secrets.LINECHANNELTOKEN }}
                COOKIE: ${{ secrets.COOKIE }}
              run: |
                echo "Install Dependencies"
                npm i
                echo "Compile scripts"
                npm run build
                echo "Make Cookies file"
                node dist/parseCookie.js make
                npm run signup
                echo "Check Cookies expired"
                node dist/parseCookie.js check
